# CONJUNTO DE DATOS IRIRS
head(iris)
# TEST DE NORMALIDAD UNIVARIADA CON SHAPIRO WILK
shapiro.test(iris[,3])

library(MVN)
# TEST NORMALIDAD MULTIVARIANTE CON HENZE-ZIRKLER, MARDIA Y ROYSTON
# HENZE-ZIRKLER
mvn(iris[,-5],mvnTest = "hz")
# ROYSTON
mvn(iris[,-5],mvnTest = "royston")
# MARDIA (CONTRASTE DE CURTOSIS Y ASIMETRIA PARA MEDIR NORMALIDAD MULTIVARIANTE)
mvn(iris[,-5],mvnTest = "mardia")